name: Terraform Apply AWS

on:
  workflow_dispatch: # permite execução manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: ./src
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        env:
          # TF_VAR_principal_user_arn: ${{ vars.AWS_PRINCIPAL_USER_ARN }}
          # TF_VAR_eks_lab_role_arn: ${{ vars.EKS_LAB_ROLE_ARN }}
          TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
          TF_VAR_rds_username: ${{ secrets.RDS_USERNAME }}
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
